/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
*/
(function(a){function q(c,e){var d=this,i=c.add(d),j=a(window),b,g,m,h=a.tools.expose&&(e.mask||e.expose),r=Math.random().toString().slice(10);if(h){if(typeof h=="string")h={color:h};h.closeOnClick=h.closeOnEsc=false}var s=e.target||c.attr("rel");g=s?a(s):c;if(!g.length)throw"Could not find Overlay: "+s;c&&c.index(g)==-1&&c.click(function(f){d.load(f);return f.preventDefault()});a.extend(d,{load:function(f){if(d.isOpened())return d;var k=o[e.effect];if(!k)throw'Overlay: cannot find effect : "'+e.effect+
'"';e.oneInstance&&a.each(n,function(){this.close(f)});f=f||a.Event();f.type="onBeforeLoad";i.trigger(f);if(f.isDefaultPrevented())return d;m=true;h&&a(g).expose(h);var l=e.top,t=e.left,u=g.outerWidth({margin:true}),v=g.outerHeight({margin:true});if(typeof l=="string")l=l=="center"?Math.max((j.height()-v)/2,0):parseInt(l,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);k[0].call(d,{top:l,left:t},function(){if(m){f.type="onLoad";i.trigger(f)}});h&&e.closeOnClick&&a.mask.getMask().one("click",
d.close);e.closeOnClick&&a(document).bind("click."+r,function(p){a(p.target).parents(g).length||d.close(p)});e.closeOnEsc&&a(document).bind("keydown."+r,function(p){p.keyCode==27&&d.close(p)});return d},close:function(f){if(!d.isOpened())return d;f=f||a.Event();f.type="onBeforeClose";i.trigger(f);if(!f.isDefaultPrevented()){m=false;o[e.effect][1].call(d,function(){f.type="onClose";i.trigger(f)});a(document).unbind("click."+r).unbind("keydown."+r);h&&a.mask.close();return d}},getOverlay:function(){return g},
getTrigger:function(){return c},getClosers:function(){return b},isOpened:function(){return m},getConf:function(){return e}});a.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(f,k){a.isFunction(e[k])&&a(d).bind(k,e[k]);d[k]=function(l){l&&a(d).bind(k,l);return d}});b=g.find(e.close||".close");if(!b.length&&!e.close){b=a('<a class="close"></a>');g.prepend(b)}b.click(function(f){d.close(f)});e.load&&d.load()}a.tools=a.tools||{version:"@VERSION"};a.tools.overlay={addEffect:function(c,
e,d){o[c]=[e,d]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!a.browser.msie||a.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var n=[],o={};a.tools.overlay.addEffect("default",function(c,e){var d=this.getConf(),i=a(window);if(!d.fixed){c.top+=i.scrollTop();c.left+=i.scrollLeft()}c.position=d.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(d.speed,e)},function(c){this.getOverlay().fadeOut(this.getConf().closeSpeed,
c)});a.fn.overlay=function(c){var e=this.data("overlay");if(e)return e;if(a.isFunction(c))c={onBeforeLoad:c};c=a.extend(true,{},a.tools.overlay.conf,c);this.each(function(){e=new q(a(this),c);n.push(e);a(this).data("overlay",e)});return c.api?e:this}})(jQuery);
(function(a){function q(){if(a.browser.msie){var b=a(document).height(),g=a(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,b-g<20?g:b]}return[a(document).width(),a(document).height()]}function n(b){if(b)return b.call(a.mask)}a.tools=a.tools||{version:"@VERSION"};var o;o=a.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var c,e,d,i,j;a.mask={load:function(b,g){if(d)return this;if(typeof b=="string")b={color:b};b=b||i;i=b=a.extend(a.extend({},o.conf),b);c=a("#"+b.maskId);if(!c.length){c=a("<div/>").attr("id",b.maskId);a("body").append(c)}var m=q();c.css({position:"absolute",top:0,left:0,width:m[0],height:m[1],display:"none",opacity:b.startOpacity,zIndex:b.zIndex});b.color&&c.css("backgroundColor",b.color);if(n(b.onBeforeLoad)===false)return this;b.closeOnEsc&&a(document).bind("keydown.mask",function(h){h.keyCode==
27&&a.mask.close(h)});b.closeOnClick&&c.bind("click.mask",function(h){a.mask.close(h)});a(window).bind("resize.mask",function(){a.mask.fit()});if(g&&g.length){j=g.eq(0).css("zIndex");a.each(g,function(){var h=a(this);/relative|absolute|fixed/i.test(h.css("position"))||h.css("position","relative")});e=g.css({zIndex:Math.max(b.zIndex+1,j=="auto"?0:j)})}c.css({display:"block"}).fadeTo(b.loadSpeed,b.opacity,function(){a.mask.fit();n(b.onLoad);d="full"});d=true;return this},close:function(){if(d){if(n(i.onBeforeClose)===
false)return this;c.fadeOut(i.closeSpeed,function(){n(i.onClose);e&&e.css({zIndex:j});d=false});a(document).unbind("keydown.mask");c.unbind("click.mask");a(window).unbind("resize.mask")}return this},fit:function(){if(d){var b=q();c.css({width:b[0],height:b[1]})}},getMask:function(){return c},isLoaded:function(b){return b?d=="full":d},getConf:function(){return i},getExposed:function(){return e}};a.fn.mask=function(b){a.mask.load(b);return this};a.fn.expose=function(b){a.mask.load(b,this);return this}})(jQuery);
