var scope=$CONFIG={};Function.prototype.bind2=function(a){var d=this;return function(){return d.apply(a,arguments)}};scope.$VERSION="t3";scope.$BASEIMG="http://img.t.sinajs.cn/"+scope.$VERSION+"/";scope.$BASECSS="http://img.t.sinajs.cn/"+scope.$VERSION+"/";scope.$BASEJS="http://js.t.sinajs.cn/"+scope.$VERSION+"/";scope.$BASESTATIC="http://js.t.sinajs.cn/"+scope.$VERSION+"/";scope._ua=navigator.userAgent.toLowerCase();scope.$IE=/msie/.test(scope._ua);scope.$OPERA=/opera/.test(scope._ua);
scope.$MOZ=/gecko/.test(scope._ua);scope.$IE5=/msie 5 /.test(scope._ua);scope.$IE55=/msie 5.5/.test(scope._ua);scope.$IE6=/msie 6/.test(scope._ua);scope.$IE7=/msie 7/.test(scope._ua);scope.$SAFARI=/safari/.test(scope._ua);scope.$winXP=/windows nt 5.1/.test(scope._ua);scope.$winVista=/windows nt 6.0/.test(scope._ua);var $IE=scope.$IE,$MOZ=scope.$MOZ,$IE6=scope.$IE6;function $import(){}var Boot={};Boot.getJsVersion=function(){var a=false;if($CONFIG)a=$CONFIG.js?$CONFIG.js:"";return a?"?v="+a:""};try{Boot.addDOMLoadEvent(main)}catch(e){}
var $Debug=function(){function a(f,h,j){var m;f=f!=null?f:"";var r={color:null,bgcolor:null,html:null};j=j!=null?j:"log";h=h!=null?h:{};for(m in r)if(h[m]!=null)r[m]=h[m];b.push({label:f,cmd:j,opts:r,time:new Date})}function d(f,h){a(f,h,"log")}var b=[];d.fatal=function(f,h){a(f,h,"fatal")};d.error=function(f,h){a(f,h,"error")};d.warning=function(f,h){a(f,h,"warning")};d.info=function(f,h){a(f,h,"info")};d.log=function(f,h){a(f,h,"log")};d.clear=function(){b=[]};d.contentList=b;return d}();
if(typeof Sina=="undefined")Sina={};Sina.pkg=function(a){if(!a||!a.length)return null;a=a.split(".");for(var d=Sina,b=a[0]=="Sina"?1:0;b<a.length;++b){d[a[b]]=d[a[b]]||{};d=d[a[b]]}return d};function $E(a){a=typeof a=="string"?document.getElementById(a):a;if(a!=null)return a;return null}function $C(a){return document.createElement(a)}try{document.execCommand("BackgroundImageCache",false,true)}catch(e$$1){}if(typeof App=="undefined")var App={};
var Jobs=function(){var a=function(b,f,h){b=typeof b==="string"?document.getElementById(b):b;if(b!=null){f=f||"click";if((typeof h).toLowerCase()=="function")if(b.attachEvent)b.attachEvent("on"+f,h);else if(b.addEventListener)b.addEventListener(f,h,false);else b["on"+f]=h}},d=function(){var b=[],f=false,h=function(){if(f!=true){f=true;for(var j=0,m=b.length;j<m;j++)(typeof b[j]).toLowerCase()=="function"&&b[j].call();b=[]}};if(document.attachEvent)(function(){try{document.documentElement.doScroll("left")}catch(j){setTimeout(arguments.callee,
0);return}h()})();else if(document.addEventListener)a(document,"DOMContentLoaded",h);else/WebKit/i.test(navigator.userAgent)&&function(){/loaded|complete/.test(document.readyState.toLowerCase())?h():setTimeout(arguments.callee,25)}();a(window,"load",h);return function(j){if(f==false)b.push(j);else(typeof j).toLowerCase()=="function"&&j.call()}}();return new (function(){var b={},f=[];this.regist=function(h,j){if(b[h]==null)b[h]=j;f.push(h)};d(function(){var h=0,j=f.length,m,r,A;(function(){if(j>h){m=
f[h];r=b[m];A=new Date;if(typeof r=="undefined")$Debug.fatal("<b>Job ["+m+"] \u672a\u5b9a\u4e49!</b>",{html:true});else{try{r.call()}catch(s){$Debug.fatal("<b>Job ["+m+"] \u6267\u884c\u5931\u8d25!</b><br/>&nbsp;"+s.name+"<br/>&nbsp;"+(s.message||s.description)+(s.fileName?"<br/>&nbsp;"+s.fileName:"")+(s.lineNumber?"<br/>&nbsp;"+s.lineNumber:""),{html:true})}finally{$Debug.info("<b>Job ["+m+"] \u6267\u884c\u6210\u529f("+(new Date-A)+"\u6beb\u79d2)</b>",{html:true})}h++;setTimeout(arguments.callee,
25)}}})()})})}();Sina.pkg("Core");if(typeof Core=="undefined")Core=Sina.Core;Sina.pkg("Core.Events");Core.Events.addEvent=function(a,d,b,f){var h=$E(a);if(h==null)$Debug("addEvent \u627e\u4e0d\u5230\u5bf9\u8c61\uff1a"+a);else{if(typeof f=="undefined")f=false;if(typeof b=="undefined")b="click";if(h.addEventListener){h.addEventListener(b,d,f);return true}else if(h.attachEvent){h.attachEvent("on"+b,d);return true}else h["on"+b]=d}};
Core.Events.removeEvent=function(a,d,b){var f=$E(a);if(f==null)$Debug("removeEvent \u627e\u4e0d\u5230\u5bf9\u8c61\uff1a"+a);else if(typeof d=="function"){if(typeof b=="undefined")b="click";if(f.addEventListener)f.removeEventListener(b,d,false);else f.attachEvent&&f.detachEvent("on"+b,d);d[b]=null}};Sina.pkg("Core.Base");
(function(){Core.Base.detect=new (function(){var a=navigator.userAgent.toLowerCase();this.$IE=/msie/.test(a);this.$OPERA=/opera/.test(a);this.$MOZ=/gecko/.test(a);this.$IE5=/msie 5 /.test(a);this.$IE55=/msie 5.5/.test(a);this.$IE6=/msie 6/.test(a);this.$IE7=/msie 7/.test(a);this.$SAFARI=/safari/.test(a);this.$winXP=/windows nt 5.1/.test(a);this.$winVista=/windows nt 6.0/.test(a);this.$FF2=/Firefox\/2/i.test(a);this.$IOS=/\((iPhone|iPad|iPod)/i.test(a)})})();Core.Events.getEvent=function(){return window.event};
if(!Core.Base.detect.$IE)Core.Events.getEvent=function(){if(window.event)return window.event;for(var a=arguments.callee.caller,d,b=0;a!=null&&b<40;){if((d=a.arguments[0])&&(d.constructor==Event||d.constructor==MouseEvent))return d;b++;a=a.caller}return d};Core.Events.stopEvent=function(a){a=a?a:Core.Events.getEvent();a.cancelBubble=true;a.returnValue=false};if(!$IE)Core.Events.stopEvent=function(a){a=a?a:Core.Events.getEvent();a.preventDefault();a.stopPropagation()};
Core.Events.fireEvent=function(a,d){a=$E(a)||a;if($IE)a.fireEvent("on"+d);else{var b=document.createEvent("HTMLEvents");b.initEvent(d,true,true);a.dispatchEvent(b)}};Sina.pkg("Core.Dom");Core.Dom.getStyle=function(a,d){switch(d){case "opacity":var b=100;try{b=a.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(f){try{b=a.filters("alpha").opacity}catch(h){}}return b/100;case "float":d="styleFloat";default:b=a.currentStyle?a.currentStyle[d]:null;return a.style[d]||b}};
if(!Core.Base.detect.$IE)Core.Dom.getStyle=function(a,d){if(d=="float")d="cssFloat";try{var b=document.defaultView.getComputedStyle(a,"")}catch(f){traceError(f)}return a.style[d]||b?b[d]:null};Sina.pkg("Core.System");Core.System.getScrollPos=function(a){a=a||document;var d=a.documentElement;a=a.body;return[Math.max(d.scrollTop,a.scrollTop),Math.max(d.scrollLeft,a.scrollLeft),Math.max(d.scrollWidth,a.scrollWidth),Math.max(d.scrollHeight,a.scrollHeight)]};
Core.Dom.getXY=function(a){if((a.parentNode==null||a.offsetParent==null||Core.Dom.getStyle(a,"display")=="none")&&a!=document.body)return false;var d;d=a.getBoundingClientRect();a=Core.System.getScrollPos(a.ownerDocument);return[d.left+a[1],d.top+a[0]]};
if(!$IE)Core.Dom.getXY=function(a){if((a.parentNode==null||a.offsetParent==null||Core.Dom.getStyle(a,"display")=="none")&&a!=document.body)return false;var d=null,b=[];b=[a.offsetLeft,a.offsetTop];d=a.offsetParent;var f=Core.Dom.getStyle(a,"position")=="absolute";if(d!=a)for(;d;){b[0]+=d.offsetLeft;b[1]+=d.offsetTop;if(scope.$SAFARI&&!f&&Core.Dom.getStyle(d,"position")=="absolute")f=true;d=d.offsetParent}if(scope.$SAFARI&&f){b[0]-=a.ownerDocument.body.offsetLeft;b[1]-=a.ownerDocument.body.offsetTop}for(d=
a.parentNode;d.tagName&&!/^body|html$/i.test(d.tagName);){if(Core.Dom.getStyle(d,"display").search(/^inline|table-row.*$/i)){b[0]-=d.scrollLeft;b[1]-=d.scrollTop}d=d.parentNode}return b};
(function(a){a.DomBuilder=function(d,b,f){f=typeof f=="object"?f:{};var h=$C("div");h.innerHTML=d;var j={};d={};var m={},r=h.getElementsByTagName("*"),A=r.length,s=f.clear||1,B=f.mm||"mm";f=f.dd||"dd";for(var E,w,x,y=0;y<A;y++){E=r[y];x=E.getAttribute(f);w=E.getAttribute(B);x&&(d[x]=E)&&s&&E.removeAttribute(f);w&&(!m[w]&&(m[w]=[E])||(m[w]=m[w].concat([E])))&&s&&E.removeAttribute(B)}j.parent=b;j.domList=d;j.actList=m;j.add=function(){for(;h.firstChild;)b.appendChild(h.firstChild);return j};return j};
a.builder3=function(d,b,f){b.innerHTML="";return a.DomBuilder(d,b,f).add()}})(App);
App.TextareaUtils=function(){var a={},d=document.selection;a.selectionStart=function(b){if(!d)return b.selectionStart;var f=d.createRange(),h=document.body.createTextRange();h.moveToElementText(b);for(b=0;h.compareEndPoints("StartToStart",f)<0;b++)h.moveStart("character",1);return b};a.selectionBefore=function(b){return b.value.slice(0,a.selectionStart(b))};a.selectText=function(b,f,h){b.focus();if(d){b=b.createTextRange();b.collapse(1);b.moveStart("character",f);b.moveEnd("character",h-f);b.select()}else b.setSelectionRange(f,
h)};a.insertText=function(b,f,h,j){b.focus();j=j||0;if(d){b=d.createRange();b.moveStart("character",-j);b.text=f}else{var m=b.value;j=h-j;var r=j+f.length;b.value=m.slice(0,j)+f+m.slice(h,m.length);a.selectText(b,r,r)}};a.getCursorPos=function(b){var f=0;if($IE){b.focus();f=null;f=d.createRange();var h=f.duplicate();h.moveToElementText(b);h.setEndPoint("EndToEnd",f);b.selectionStart=h.text.length-f.text.length;b.selectionEnd=b.selectionStart+f.text.length;f=b.selectionStart}else if(b.selectionStart||
b.selectionStart=="0")f=b.selectionStart;return f};a.getSelectedText=function(b){var f="";return f=window.getSelection?b.selectionStart!=undefined&&b.selectionEnd!=undefined?b.value.substring(b.selectionStart,b.selectionEnd):"":d.createRange().text};a.setCursor=function(b,f,h){f=f==null?b.value.length:f;h=h==null?0:h;b.focus();if(b.createTextRange){b=b.createTextRange();b.move("character",f);b.moveEnd("character",h);b.select()}else b.setSelectionRange(f,f+h)};a.unCoverInsertText=function(b,f,h){h=
h==null?{}:h;h.rcs=h.rcs==null?b.value.length:h.rcs*1;h.rccl=h.rccl==null?0:h.rccl*1;var j=b.value,m=j.slice(0,h.rcs);j=j.slice(h.rcs+h.rccl,j==""?0:j.length);b.value=m+f+j;this.setCursor(b,h.rcs+(f==null?0:f.length))};return a}();
App.simpleAjax=function(a,d,b,f){var h,j;if(h=window.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):new XMLHttpRequest){h.onreadystatechange=function(){try{if(h.readyState==4)if((j=eval("("+h.responseText+")"))&&j.code=="A00006")d&&d(j);else b&&b(j)}catch(r){f&&f(r.message);return false}};try{h.open("GET",a,true);h.send(null)}catch(m){f&&f(m.message);return false}return{abort:function(){h.abort();return false}}}};
App.unit=function(){var a={};a.u=u=function(d,b){var f={it:a,sup:a[b]};return function(){d.apply(f,arguments);return a}};return a};
(function(a){var d=document,b=1E3;a.PopUp=function(){var f=App.unit(),h=f.u,j,m,r,A=App.removeChildren;f.wrap=j=$C("div");j.appendChild(f.body=m=$C("div"));j.style.cssText=["position:absolute;clear:both;;visibility:hidden;display:none","z-index:"+b++].join(";");f.mask=h(function(){if(!r){j.insertBefore(r=$C("iframe"),m);r.frameborder=0;r.src="about:blank";r.style.cssText="position:absolute;clear:both;;width:100%;height:100%;filter:alpha(opacity=0);opacity:0;z-index:-1"}});f.content=h(function(s){A(m);
f.dom=App.builder3(s,m,{dd:"id",mm:"action"}).domList});f.position=h(function(s,B){j.style.left=s+"px";j.style.top=B+"px"});f.visible=h(function(s){j.style.visibility=s?"visible":"hidden";j.style.display=s?"":"none"});f.zIndex=h(function(s){j.style.zIndex=s});f.destroy=h(function(){j.parentNode.removeChild(j);j=m=r=dom=null});d.body.appendChild(j);return f}})(App);
var swfobject=function(){function a(){if(!J){try{var c=o.getElementsByTagName("body")[0].appendChild(o.createElement("span"));c.parentNode.removeChild(c)}catch(g){return}J=true;c=X.length;for(var i=0;i<c;i++)X[i]()}}function d(c){if(J)c();else X[X.length]=c}function b(c){if(typeof K.addEventListener!=z)K.addEventListener("load",c,false);else if(typeof o.addEventListener!=z)o.addEventListener("load",c,false);else if(typeof K.attachEvent!=z)x(K,"onload",c);else if(typeof K.onload=="function"){var g=
K.onload;K.onload=function(){g();c()}}else K.onload=c}function f(){var c=o.getElementsByTagName("body")[0],g=o.createElement(G);g.setAttribute("type",R);var i=c.appendChild(g);if(i){var k=0;(function(){if(typeof i.GetVariable!=z){var l=i.GetVariable("$version");if(l){l=l.split(" ")[1].split(",");n.pv=[parseInt(l[0],10),parseInt(l[1],10),parseInt(l[2],10)]}}else if(k<10){k++;setTimeout(arguments.callee,10);return}c.removeChild(g);i=null;h()})()}else h()}function h(){var c=O.length;if(c>0)for(var g=
0;g<c;g++){var i=O[g].id,k=O[g].callbackFn,l={success:false,id:i};if(n.pv[0]>0){var q=w(i);if(q)if(y(O[g].swfVersion)&&!(n.wk&&n.wk<312)){H(i,true);if(k){l.success=true;l.ref=j(i);k(l)}}else if(O[g].expressInstall&&m()){l={};l.data=O[g].expressInstall;l.width=q.getAttribute("width")||"0";l.height=q.getAttribute("height")||"0";if(q.getAttribute("class"))l.styleclass=q.getAttribute("class");if(q.getAttribute("align"))l.align=q.getAttribute("align");var p={};q=q.getElementsByTagName("param");for(var v=
q.length,t=0;t<v;t++)if(q[t].getAttribute("name").toLowerCase()!="movie")p[q[t].getAttribute("name")]=q[t].getAttribute("value");r(l,p,i,k)}else{A(q);k&&k(l)}}else{H(i,true);if(k){if((i=j(i))&&typeof i.SetVariable!=z){l.success=true;l.ref=i}k(l)}}}}function j(c){var g=null;if((c=w(c))&&c.nodeName=="OBJECT")if(typeof c.SetVariable!=z)g=c;else if(c=c.getElementsByTagName(G)[0])g=c;return g}function m(){return!S&&y("6.0.65")&&(n.win||n.mac)&&!(n.wk&&n.wk<312)}function r(c,g,i,k){S=true;T=k||null;V={success:false,
id:i};var l=w(i);if(l){if(l.nodeName=="OBJECT"){U=s(l);aa=null}else{U=l;aa=i}c.id=ga;if(typeof c.width==z||!/%$/.test(c.width)&&parseInt(c.width,10)<310)c.width="310";if(typeof c.height==z||!/%$/.test(c.height)&&parseInt(c.height,10)<137)c.height="137";o.title=o.title.slice(0,47)+" - Flash Player Installation";k=n.ie&&n.win?"ActiveX":"PlugIn";k="MMredirectURL="+K.location.toString().replace(/&/g,"%26")+"&MMplayerType="+k+"&MMdoctitle="+o.title;if(typeof g.flashvars!=z)g.flashvars+="&"+k;else g.flashvars=
k;if(n.ie&&n.win&&l.readyState!=4){k=o.createElement("div");i+="SWFObjectNew";k.setAttribute("id",i);l.parentNode.insertBefore(k,l);l.style.display="none";(function(){l.readyState==4?l.parentNode.removeChild(l):setTimeout(arguments.callee,10)})()}B(c,g,i)}}function A(c){if(n.ie&&n.win&&c.readyState!=4){var g=o.createElement("div");c.parentNode.insertBefore(g,c);g.parentNode.replaceChild(s(c),g);c.style.display="none";(function(){c.readyState==4?c.parentNode.removeChild(c):setTimeout(arguments.callee,
10)})()}else c.parentNode.replaceChild(s(c),c)}function s(c){var g=o.createElement("div");if(n.win&&n.ie)g.innerHTML=c.innerHTML;else if(c=c.getElementsByTagName(G)[0])if(c=c.childNodes)for(var i=c.length,k=0;k<i;k++)!(c[k].nodeType==1&&c[k].nodeName=="PARAM")&&c[k].nodeType!=8&&g.appendChild(c[k].cloneNode(true));return g}function B(c,g,i){var k,l=w(i);if(n.wk&&n.wk<312)return k;if(l){if(typeof c.id==z)c.id=i;if(n.ie&&n.win){var q="";for(var p in c)if(c[p]!=Object.prototype[p])if(p.toLowerCase()==
"data")g.movie=c[p];else if(p.toLowerCase()=="styleclass")q+=' class="'+c[p]+'"';else if(p.toLowerCase()!="classid")q+=" "+p+'="'+c[p]+'"';p="";for(var v in g)if(g[v]!=Object.prototype[v])p+='<param name="'+v+'" value="'+g[v]+'" />';l.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+q+">"+p+"</object>";Y[Y.length]=c.id;k=w(c.id)}else{v=o.createElement(G);v.setAttribute("type",R);for(var t in c)if(c[t]!=Object.prototype[t])if(t.toLowerCase()=="styleclass")v.setAttribute("class",
c[t]);else t.toLowerCase()!="classid"&&v.setAttribute(t,c[t]);for(q in g)if(g[q]!=Object.prototype[q]&&q.toLowerCase()!="movie"){c=v;p=q;t=g[q];i=o.createElement("param");i.setAttribute("name",p);i.setAttribute("value",t);c.appendChild(i)}l.parentNode.replaceChild(v,l);k=v}}return k}function E(c){var g=w(c);if(g&&g.nodeName=="OBJECT")if(n.ie&&n.win){g.style.display="none";(function(){if(g.readyState==4){var i=w(c);if(i){for(var k in i)if(typeof i[k]=="function")i[k]=null;i.parentNode.removeChild(i)}}else setTimeout(arguments.callee,
10)})()}else g.parentNode.removeChild(g)}function w(c){var g=null;try{g=o.getElementById(c)}catch(i){}return g}function x(c,g,i){c.attachEvent(g,i);W[W.length]=[c,g,i]}function y(c){var g=n.pv;c=c.split(".");c[0]=parseInt(c[0],10);c[1]=parseInt(c[1],10)||0;c[2]=parseInt(c[2],10)||0;return g[0]>c[0]||g[0]==c[0]&&g[1]>c[1]||g[0]==c[0]&&g[1]==c[1]&&g[2]>=c[2]?true:false}function P(c,g,i,k){if(!(n.ie&&n.mac)){var l=o.getElementsByTagName("head")[0];if(l){i=i&&typeof i=="string"?i:"screen";if(k)da=N=null;
if(!N||da!=i){k=o.createElement("style");k.setAttribute("type","text/css");k.setAttribute("media",i);N=l.appendChild(k);if(n.ie&&n.win&&typeof o.styleSheets!=z&&o.styleSheets.length>0)N=o.styleSheets[o.styleSheets.length-1];da=i}if(n.ie&&n.win)N&&typeof N.addRule==G&&N.addRule(c,g);else N&&typeof o.createTextNode!=z&&N.appendChild(o.createTextNode(c+" {"+g+"}"))}}}function H(c,g){if(ea){var i=g?"visible":"hidden";if(J&&w(c))w(c).style.visibility=i;else P("#"+c,"visibility:"+i)}}function ba(c){return/[\\\"<>\.;]/.exec(c)!=
null&&typeof encodeURIComponent!=z?encodeURIComponent(c):c}var z="undefined",G="object",R="application/x-shockwave-flash",ga="SWFObjectExprInst",K=window,o=document,Q=navigator,ha=false,X=[function(){ha?f():h()}],O=[],Y=[],W=[],U,aa,T,V,J=false,S=false,N,da,ea=true,n=function(){var c=typeof o.getElementById!=z&&typeof o.getElementsByTagName!=z&&typeof o.createElement!=z,g=Q.userAgent.toLowerCase(),i=Q.platform.toLowerCase(),k=i?/win/.test(i):/win/.test(g);i=i?/mac/.test(i):/mac/.test(g);g=/webkit/.test(g)?
parseFloat(g.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;var l=!+"\u000b1",q=[0,0,0],p=null;if(typeof Q.plugins!=z&&typeof Q.plugins["Shockwave Flash"]==G){if((p=Q.plugins["Shockwave Flash"].description)&&!(typeof Q.mimeTypes!=z&&Q.mimeTypes[R]&&!Q.mimeTypes[R].enabledPlugin)){ha=true;l=false;p=p.replace(/^.*\s+(\S+\s+\S+$)/,"$1");q[0]=parseInt(p.replace(/^(.*)\..*$/,"$1"),10);q[1]=parseInt(p.replace(/^.*\.(.*)\s.*$/,"$1"),10);q[2]=/[a-zA-Z]/.test(p)?parseInt(p.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0}}else if(typeof K.ActiveXObject!=z)try{var v=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(v)if(p=v.GetVariable("$version")){l=true;p=p.split(" ")[1].split(",");q=[parseInt(p[0],10),parseInt(p[1],10),parseInt(p[2],10)]}}catch(t){}return{w3:c,pv:q,wk:g,ie:l,win:k,mac:i}}();(function(){if(n.w3){if(typeof o.readyState!=z&&o.readyState=="complete"||typeof o.readyState==z&&(o.getElementsByTagName("body")[0]||o.body))a();if(!J){typeof o.addEventListener!=z&&o.addEventListener("DOMContentLoaded",
a,false);if(n.ie&&n.win){o.attachEvent("onreadystatechange",function(){if(o.readyState=="complete"){o.detachEvent("onreadystatechange",arguments.callee);a()}});K==top&&function(){if(!J){try{o.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,0);return}a()}}()}n.wk&&function(){J||(/loaded|complete/.test(o.readyState)?a():setTimeout(arguments.callee,0))}();b(a)}}})();(function(){n.ie&&n.win&&window.attachEvent("onunload",function(){for(var c=W.length,g=0;g<c;g++)W[g][0].detachEvent(W[g][1],
W[g][2]);c=Y.length;for(g=0;g<c;g++)E(Y[g]);for(var i in n)n[i]=null;n=null;for(var k in swfobject)swfobject[k]=null;swfobject=null})})();return{registerObject:function(c,g,i,k){if(n.w3&&c&&g){var l={};l.id=c;l.swfVersion=g;l.expressInstall=i;l.callbackFn=k;O[O.length]=l;H(c,false)}else k&&k({success:false,id:c})},getObjectById:function(c){if(n.w3)return j(c)},embedSWF:function(c,g,i,k,l,q,p,v,t,L){var I={success:false,id:g};if(n.w3&&!(n.wk&&n.wk<312)&&c&&g&&i&&k&&l){H(g,false);d(function(){i+="";
k+="";var D={};if(t&&typeof t===G)for(var C in t)D[C]=t[C];D.data=c;D.width=i;D.height=k;C={};if(v&&typeof v===G)for(var F in v)C[F]=v[F];if(p&&typeof p===G)for(var M in p)if(typeof C.flashvars!=z)C.flashvars+="&"+M+"="+p[M];else C.flashvars=M+"="+p[M];if(y(l)){F=B(D,C,g);D.id==g&&H(g,true);I.success=true;I.ref=F}else if(q&&m()){D.data=q;r(D,C,g,L);return}else H(g,true);L&&L(I)})}else L&&L(I)},switchOffAutoHideShow:function(){ea=false},ua:n,getFlashPlayerVersion:function(){return{major:n.pv[0],minor:n.pv[1],
release:n.pv[2]}},hasFlashPlayerVersion:y,createSWF:function(c,g,i){if(n.w3)return B(c,g,i)},showExpressInstall:function(c,g,i,k){n.w3&&m()&&r(c,g,i,k)},removeSWF:function(c){n.w3&&E(c)},createCSS:function(c,g,i,k){n.w3&&P(c,g,i,k)},addDomLoadEvent:d,addLoadEvent:b,getQueryParamValue:function(c){var g=o.location.search||o.location.hash;if(g){if(/\?/.test(g))g=g.split("?")[1];if(c==null)return ba(g);g=g.split("&");for(var i=0;i<g.length;i++)if(g[i].substring(0,g[i].indexOf("="))==c)return ba(g[i].substring(g[i].indexOf("=")+
1))}return""},expressInstallCallback:function(){if(S){var c=w(ga);if(c&&U){c.parentNode.replaceChild(U,c);if(aa){H(aa,true);if(n.ie&&n.win)U.style.display="block"}T&&T(V)}S=false}}}}();Core.Dom.setStyle=function(a,d,b){switch(d){case "opacity":a.style.filter="alpha(opacity="+b*100+")";if(!a.currentStyle||!a.currentStyle.hasLayout)a.style.zoom=1;break;case "float":d="styleFloat";default:a.style[d]=b}};
if(!Core.Base.detect.$IE)Core.Dom.setStyle=function(a,d,b){if(d=="float")d="cssFloat";a.style[d]=b};Core.System.winSize=function(a){var d,b;target=a?a.document:document;if(self.innerHeight){target=a?a.self:self;d=target.innerWidth;b=target.innerHeight}else if(target.documentElement&&target.documentElement.clientHeight){d=target.documentElement.clientWidth;b=target.documentElement.clientHeight}else if(target.body){d=target.body.clientWidth;b=target.body.clientHeight}return{width:d,height:b}};
Core.System.pageSize=function(a){target=a?a.document:document;var d=target.compatMode=="CSS1Compat"?target.documentElement:target.body,b;if(window.innerHeight&&window.scrollMaxY){b=d.scrollWidth;d=window.innerHeight+window.scrollMaxY}else if(d.scrollHeight>d.offsetHeight){b=d.scrollWidth;d=d.scrollHeight}else{b=d.offsetWidth;d=d.offsetHeight}a=Core.System.winSize(a);pageHeight=d<a.height?a.height:d;pageWidth=b<a.width?a.width:b;return[pageWidth,pageHeight,a.width,a.height]};
App.iframeMask=function(a,d){var b={},f=b.oParent=document.getElementsByTagName("body")[0],h=b.oMask=f.appendChild($C("div"));f=b.oProtective=f.appendChild($C("iframe"));f.frameborder=0;var j=h.style,m=f.style;m=f.style;j.top=m.top="0px";j.left=m.left="0px";j.overflow=m.overflow="hidden";j.border=m.border="0px";j.position=m.position="absolute";j.display=m.display="none";j.backgroundColor=m.backgroundColor="#000000";j.zIndex=a||799;m.zIndex=a-1||798;Core.Dom.setStyle(h,"opacity","0.15");Core.Dom.setStyle(f,
"opacity","0");b.oMaskResize=function(r){return function(){var A=Core.System.pageSize();r.oMask.style.width=r.oProtective.style.width=Math.max(document.body.scrollWidth,document.documentElement?document.documentElement.scrollWidth:0)+"px";r.oMask.style.height=r.oProtective.style.height=A[1]+"px";d&&d(A)}}(b);b.hidden=function(r){return function(){r.oMask.style.display=r.oProtective.style.display="none"}}(b);b.show=function(r){return function(){r.oMask.style.display=r.oProtective.style.display="block"}}(b);
b.oMaskResize();Core.Events.addEvent(window,b.oMaskResize,"resize");return b};
App.PopUpSwfPlayer=function(){var a,d,b,f,h=Core.Events,j=h.addEvent,m=h.removeEvent;return function(r){var A=window,s=document,B=s.documentElement||{},E=s.body;scope.statistics&&scope.statistics({type:"ani",source:encodeURIComponent(r)});if(swfobject.hasFlashPlayerVersion("9.0.0")){if(!d){document.body.appendChild(d=$C("div"));d.style.position="absolute";d.style.zIndex="2012"}d.style.display="";if(!b){d.innerHTML="";d.appendChild(b=$C("div"));b.id="view_ani";b.innerHTML=['<div style="padding-left:202px;padding-top:172px;"><center><img src="',
[scope.$BASECSS,"style/images/common/loading.gif"].join(""),'"/></center></div>'].join("")}s=function(x){var y=A.pageYOffset||Math.max(B.scrollTop,E.scrollTop);d.style.left=(x[2]-440)/2+"px";d.style.top=(x[3]-360)/2+y+"px"};if(a)s(Core.System.pageSize());else a=App.iframeMask(2E3,s);var w=function(x){if(!(x&&x.keyCode!==27&&x.type!=="mouseup")){clearInterval(f);swfobject.removeSWF("view_ani");d.style.display="none";b=null;a.hidden();m(E,w,"keyup");m(E,w,"mouseup");x&&Core.Events.stopEvent()}};swfobject.embedSWF(r,
"view_ani","440","360","10.0.0",null,{playMovie:"true"},{id:"view_ani",quality:"high",allowScriptAccess:"never",wmode:"transparent",allowFullscreen:true,allownetworking:"internal"});a.show();A.clearInterval(f);f=setInterval(function(){var x=swfobject.getObjectById("view_ani"),y=0;if(x&&x.PercentLoaded()==100){A.clearInterval(f);f=setInterval(function(){var P=x.CurrentFrame(),H;try{H=x.TotalFrames()}catch(ba){H=x.TotalFrames}if(!(P<0))if(P<H&&y<=P)y=P;else w()},80)}},100);j(E,w,"keyup");j(a.oMask,
w,"mouseup");a.oMask.title="\u70b9\u51fb\u5173\u95ed"}else App.alert({code:"\u60a8\u8fd8\u672a\u5b89\u88c5flash\u64ad\u653e\u5668\uff01"})}}();App.group=function(a,d,b){var f={},h=a.length,j,m,r=Core.Events.addEvent;f.current=-1;f.items=a;j=b&&b.selected||null;m=b&&b.unselected||null;for(var A=0;A<h;A++)(function(s,B){r(s,function(){if(!(f.current==B&&b)){m&&f.current!=-1&&(a[f.current].className=m);j&&(s.className=j);f.current=B;d(s,B,f);return false}},"mouseup")})(a[A],A)};
App.removeChildren=function(a){for(var d;d=a.firstChild;)a.removeChild(d)};Sina.pkg("Core.String");Core.String.byteLength=function(a){if(typeof a=="undefined")return 0;var d=a.match(/[^\x00-\x80]/g);return a.length+(!d?0:d.length)};Core.String.leftB=function(a,d){var b=a.replace(/\*/g," ").replace(/[^\x00-\xff]/g,"**");a=a.slice(0,b.slice(0,d).replace(/\*\*/g," ").replace(/\*/g,"").length);if(Core.String.byteLength(a)>d)a=a.slice(0,a.length-1);return a};
(function(){function a(x,y){return App.builder3(x,y,{dd:"id",mm:"action"})}var d=document,b=Core.Events,f=Core.String,h=b.stopEvent,j=b.addEvent,m=b.fireEvent,r=App.simpleAjax,A=Core.Dom.getXY,s=App.group,B=App.removeChildren,E=App.PopUp,w;App.showFaces=function(){var x={},y,P=false,H=false,ba,z={selected:"cur",unselected:" "};splitHTML='<li class="magiclicur" style="visibility:hidden">|</li>';panelHTML='<table class="mBlogLayer"><tbody><tr><td class="top_l"></td><td class="top_c"></td><td class="top_r"></td></tr><tr><td class="mid_l"></td><td class="mid_c"><div class="layerBox phiz_layerN"><div class="layerBoxTop"><div class="layerArrow" style="left:6px;"></div><div class="topCon"><ul class="phiz_menu"><li id="face" class="cur"><a href="#" onclick="this.blur();return false;">\u5e38\u7528\u8868\u60c5</a></li><li id="ani" act="topTab" class="magic"><a href="#" onclick="this.blur();return false;"><strong></strong>\u9b54\u6cd5\u8868\u60c5</a></li></ul><a id="close" href="#" onclick="return false;" title="\u5173\u95ed" class="close"></a><div class="clearit"></div></div></div><div class="magicT"><div class="magicTL"><ul id="tab"></ul></div><div class="magicTR"><a href="#" onclick="return false;" id="prevBtn" class="magicbtnL02" title="\u4e0a\u4e00\u9875"></a><a href="#" onclick="return false;" id="nextBtn" title="\u4e0b\u4e00\u9875" class="magicbtnR02"></a></div><div class="clear"></div></div><div class="layerBoxCon" style="width:450px;"><div id="hotPanel" class="faceItemPicbgT"><ul id="hot"></ul><div class="clearit"></div></div><div id="normPanel" class="faceItemPicbg"><ul id="norm"></ul><div class="clearit"></div></div><div id="pagePanel" class="magicB"><div id="magicNotes" class="magic_tit" style="display:none">\u70b9\u51fb<em class="play_btn2"></em>\u9884\u89c8\u9b54\u6cd5\u52a8\u753b</div><div class="pages" id="pageing"></div></div></div></div></td><td class="mid_r"></td></tr><tr><td class="bottom_l"></td><td class="bottom_c"></td><td class="bottom_r"></td></tr></tbody></table>';
return function(G,R,ga,K,o,Q,ha){if(G.tagName=="A")G.href="####";ba=ha||function(){return false};if(!P){y=E().zIndex(1500).content(panelHTML);o=y.dom;var X=o.close,O=o.hot,Y=o.hotPanel,W=o.magicNotes,U=o.norm,aa=o.normPanel,T=o.pageing,V=o.prevBtn,J=o.nextBtn,S=o.tab;face=o.face;ani=o.ani;cType=1;tabIndex=0;var N=function(c,g){B(g);for(var i=c.length,k=[],l,q="",p="",v,t=0;t<i;t++){l=c[t];v=l.title.replace(/[^\w\u4e00-\u9fa5\uff10-\uff19\uff21-\uff3a\uff41-\uff5a\u2014\uff3f]/g,"");cType==1&&(q='class="face_box"');
cType==1&&(p='<a action="play" title="\u8868\u60c5\u9884\u89c8" class="play_btn" href="#" onclick="return false;"></a><span class="face_box_tex">'+(f.byteLength(v)>8?f.leftB(v,6)+"...":v)+"</span>");k.push(['<li action="icon" title="',v,'"><a href="#" onclick="return false;" ',q,'><img src="',l.icon,'"/></a>',p,"</li>"].join(""))}k=a(k.join(""),g).actList;i=k.icon;(k=k.play)&&s(k,function(L,I){L.onclick=function(){return false};h();App.PopUpSwfPlayer(c[I].src);return false});s(i,function(L,I){L.onclick=
function(){return false};setTimeout(function(){tArea.focus()},0);setTimeout(function(){tArea.getAttribute("range");var D=c[I].value+" ";if(!ba(D))if(document.selection){var C=document.selection.createRange();document.selection.empty();C.text=D}else if(tArea.setSelectionRange){C=tArea.selectionEnd;var F=tArea.value.substring(0,tArea.selectionStart);C=tArea.value.substring(C);D=F+D;F=D.length;tArea.value=D+C;tArea.setSelectionRange(F,F)}else tArea.value+=D;reflush&&reflush();y.visible(false)},200);
return false})},da=function(c){B(T);var g=c.length,i=[];if(g){for(var k=0;k<g;k++)i.push('<a action="pageBtn" href="#" onclick="return false;">'+(k+1)+"</a>");g=a(i.join(""),T).actList.pageBtn;s(g,function(l,q){l.onclick=function(){return false};Y.style.display=!cType&&!tabIndex&&!q?"":"none";setTimeout(function(){N(c[q],U)},50);l.blur()},z);T.style.display=g.length<2?"none":"";m(g[0],"mouseup")}},ea=function(c){B(S);var g=[{type:"\u9ed8\u8ba4",icon:c.data.norm}].concat(c.data.more);c=g.length;for(var i,
k=[],l=0;l<c;l++)(i=g[l])&&i.type&&k.push('<li style="visibility:hidden"><a action="tabs" onclick="return false;" href="#">'+i.type+"</a></li>");if(k.length){c=a(k.join(splitHTML),S).actList.tabs;s(c,function(C,F){C.onclick=function(){return false};tabIndex=F;da(g[F].icon);C.blur()},{selected:"magicTcur",unselected:" "});m(c[0],"mouseup");var q=1,p=S.getElementsByTagName("li"),v=p.length,t=[],L=0,I=[],D;setTimeout(function(){function C(ca,fa){for(var Z=ca.length,ja=Math.max(Z-1,0),$=0;$<Z;$++){ca[$].style.visibility=
fa?"visible":"hidden";ca[$].style.display=!fa?"none":($==0||$==ja)&&ca[$].innerHTML=="|"?"none":""}}function F(ca,fa){var Z=Math[ca](q+fa,fa>0?D:0);if(q!=Z){t[q]&&C(t[q],false);t[Z]&&C(t[Z],true);q=Z}V.className=q==0?"magicbtnL01":"magicbtnL02";J.className=q==D?"magicbtnR01":"magicbtnR02"}for(var M=0;M<v;M++){p[M].style.visibility="visible";p[M].style.display="";var ia=p[M].innerHTML=="|"?8:p[M].offsetWidth;if(L+ia>400){L=0;t.push(I);I=[]}p[M].style.display="none";I.push(p[M]);L+=ia}I.length&&t.push(I);
D=t.length-1;V.onclick=function(){F("max",-1);V.blur();return false};J.onclick=function(){F("min",1);J.blur();return false};F("max",-1)},100)}};s([face,ani],function(c,g){h();c.onclick=function(){return false};B(U);B(S);B(T);face.className=g?"":"cur";ani.className=g?"magic cur":"magic";aa.className=g?"magic_list":"faceItemPicbg";Y.style.display=g?"none":"";W.style.display=g?"":"none";T.style.display="none";V.className="magicbtnL01";J.className="magicbtnR01";V.onclick=function(){return false};J.onclick=
function(){return false};cType=g;w&&w.abort();if(x[g]){ea(x[g]);return false}U.innerHTML='<center><img style="margin-top:10px;margin-bottom:10px" src="'+scope.$BASEIMG+'style/images/common/loading.gif"/></center>';w=r("/time/app/emotion.php?type="+(g?"ani":"face"),function(i){var k;if(i.code=="A00006"&&(k=i.data)){ea(i);if(!H&&k.hot){H=true;N(k.hot,O)}x[g]=i}});c.blur();return false});P=true;j(X,function(){X.onclick=function(){return false};y.visible(false);h()},"mouseup");j(y.wrap,function(){h()},
"mouseup");j(d.body,function(){y.visible(false)},"mouseup");var n=Core.System.winSize();j(window,function(){var c=Core.System.winSize();if(n.width!=c.width||n.height!=c.height){y.visible(false);n=c}},"resize")}tArea=R;reflush=Q;R=A(G);y.position(R[0]+19+(ga||0),R[1]+G.offsetHeight+(K||5));m(face,"mouseup");setTimeout(function(){y.visible(true)},0);return false}}()})();
